spring.application.name=hospital_support

# 1. DataSource Configuration - ?ã s?a thành tên database 'hospital'
spring.datasource.url=jdbc:mysql://localhost:3306/hospital?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12344321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. SQL Init Configuration
# Chuy?n thành 'never' n?u b?n ?ã ch?y script SQL th? công ?? tránh ghi ?è d? li?u
spring.sql.init.mode=never