name: Notify Discord on Push
on:
  push:
    branches:
      - "*"
jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi thông báo lên Discord
        run: |
          TIMESTAMP=$(date +"%d/%m/%Y %H:%M:%S")
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"📌 Commit mới!\n📁 Repo: ${{ github.repository }}\n🌿 Nhánh: ${{ github.ref_name }}\n👤 Tác giả: ${{ github.event.head_commit.author.name }}\n📝 Nội dung: ${{ github.event.head_commit.message }}\n\n🕒 Thời gian: ${TIMESTAMP}\n🔗 Link: ${{ github.event.head_commit.url }}\"
          }" \
          "${{ secrets.DISCORD_WEBHOOK }}"
